# DEFAULT parameters
name: "DEFAULT"   # MUST BE 'DEFAULT'
path: "../packerl_out"   # location to save results in
iterations: 1
repetitions: 16
reps_per_job: 8
reps_in_parallel: 8

params:
  use_wandb: true
  use_n_last_obs: 4
  spf_pretraining: 5
  reward_preset: "r"

list:
  synnet_custom_cfg:
    train:
      events:
        traffic:
          prob_tcp: [ 0, 0, 1.0, 1.0 ]
          traffic_scaling: [0.75, 3.0, 0.75, 3.0]
    eval:
      events:
        traffic:
          prob_tcp: [ 0, 0, 1.0, 1.0 ]
          traffic_scaling: [0.75, 3.0, 0.75, 3.0]

---

name: "fieldlines_feat_default"

params:
    node_features: "none"
    edge_features: "load_config_srd"
    global_features: "load_dj_srdr"

---

name: "fieldlines_feat_all_dim12"

params:
  node_features: "srr"
  edge_features: "load_config_srd"
  global_features: "load_dj_srdr"

---

name: "fieldlines_feat_all_dim24"

params:
  node_features: "srr"
  edge_features: "load_config_srd"
  global_features: "load_dj_srdr"
  nn:
    latent_dimension: 24

---

name: "fieldlines_feat_edge_no_srd"

params:
  node_features: "none"
  edge_features: "load_config"
  global_features: "load_dj_srdr"

---

name: "fieldlines_feat_edge_no_config"

params:
  node_features: "none"
  edge_features: "load_srd"
  global_features: "load_dj_srdr"

---

name: "fieldlines_feat_edge_no_load"

params:
  node_features: "none"
  edge_features: "config_srd"
  global_features: "load_dj_srdr"

---

name: "fieldlines_feat_edge_no_srd_config"

params:
  node_features: "none"
  edge_features: "load"
  global_features: "load_dj_srdr"

---

name: "fieldlines_feat_edge_none"

params:
  node_features: "none"
  edge_features: "none"
  global_features: "load_dj_srdr"

---

name: "fieldlines_feat_global_no_srdr"

params:
  node_features: "none"
  edge_features: "load_config_srd"
  global_features: "load_dj"

---

name: "fieldlines_feat_global_no_dj"

params:
  node_features: "none"
  edge_features: "load_config_srd"
  global_features: "load_srdr"
  
---

name: "fieldlines_feat_global_no_load"

params:
  node_features: "none"
  edge_features: "load_config_srd"
  global_features: "dj_srdr"

---

name: "fieldlines_feat_global_no_srdr_dj"

params:
  node_features: "none"
  edge_features: "load_config_srd"
  global_features: "load"

---

name: "fieldlines_feat_global_none"

params:
  node_features: "none"
  edge_features: "load_config_srd"
  global_features: "none"

---

name: "fieldlines_feat_no_load"

params:
  node_features: "srr"
  edge_features: "config_srd"
  global_features: "dj_srdr"

---

name: "fieldlines_feat_node_srd"

params:
  node_features: "srr"
  edge_features: "load_config"
  global_features: "load_dj"

---

name: "fieldlines_feat_node_not_edge_srr"

params:
  node_features: "srr"
  edge_features: "load_config"
  global_features: "load_dj_srdr"

---

name: "fieldlines_feat_load_only"

params:
  node_features: "none"
  edge_features: "load"
  global_features: "load"

---

name: "fieldlines_feat_srd_only"

params:
  node_features: "none"
  edge_features: "srd"
  global_features: "srdr"

---

name: "fieldlines_feat_no_srd"

params:
  node_features: "none"
  edge_features: "load_config"
  global_features: "load_dj"