# DEFAULT parameters
name: "DEFAULT"   # MUST BE 'DEFAULT'
path: "../packerl_out"   # location to save results in
iterations: 1
repetitions: 16
reps_per_job: 8
reps_in_parallel: 8

params:
  use_wandb: true
  scenario_presets:
    eval:
      topology:
        graph: "random_S"

list:
  synnet_custom_cfg:
    train:
      events:
        traffic:
          prob_tcp: [ 0, 0, 1.0, 1.0 ]
          traffic_scaling: [0.75, 3.0, 0.75, 3.0]
    eval:
      events:
        traffic:
          prob_tcp: [ 0, 0, 1.0, 1.0 ]
          traffic_scaling: [0.75, 3.0, 0.75, 3.0]

---

name: "fieldlines_topology_default"

params:
  use_n_last_obs: 4
  spf_pretraining: 5
  reward_preset: "r"
  scenario_presets:
    train:
      topology:
          graph: "random_XS"

---

name: "fieldlines_topology_random_S"

params:
  use_n_last_obs: 4
  spf_pretraining: 5
  reward_preset: "r"
  scenario_presets:
    train:
      topology:
        graph: "random_S"

---

name: "fieldlines_topology_mng"

params:
  use_n_last_obs: 4
  spf_pretraining: 5
  reward_preset: "r"
  scenario_presets:
    train:
      topology:
        graph: "magnneto_nsfnet_geant2"

---

name: "mslim_topology_default"

params:
  actor_critic_mode: "link_weight_gaussian"
  actor_mode: "magnneto_slim"
  global_features: "none"
  edge_features: "LU"
  link_weights_as_input: True
  initial_exploration_coeff: -1.0
  scenario_presets:
    train:
      topology:
        graph: "random_XS"

---

name: "mslim_topology_random_S"

params:
  actor_critic_mode: "link_weight_gaussian"
  actor_mode: "magnneto_slim"
  global_features: "none"
  edge_features: "LU"
  link_weights_as_input: True
  initial_exploration_coeff: -1.0
  scenario_presets:
    train:
      topology:
        graph: "random_S"

---

name: "mslim_topology_mng"

params:
  actor_critic_mode: "link_weight_gaussian"
  actor_mode: "magnneto_slim"
  global_features: "none"
  edge_features: "LU"
  link_weights_as_input: True
  initial_exploration_coeff: -1.0
  scenario_presets:
    train:
      topology:
        graph: "magnneto_nsfnet_geant2"

---

name: "mlike_topology_default"

params:
  actor_critic_mode: "link_weight_gaussian"
  actor_mode: "magnneto_like"
  critic_mode: "magnneto_like"
  global_features: "none"
  edge_features: "LU"
  link_weights_as_input: True
  initial_exploration_coeff: -1.0
  scenario_presets:
    train:
      topology:
        graph: "random_XS"

---

name: "mlike_topology_random_S"

params:
  actor_critic_mode: "link_weight_gaussian"
  actor_mode: "magnneto_like"
  critic_mode: "magnneto_like"
  global_features: "none"
  edge_features: "LU"
  link_weights_as_input: True
  initial_exploration_coeff: -1.0
  scenario_presets:
    train:
      topology:
        graph: "random_S"

---

name: "mlike_topology_mng"

params:
  actor_critic_mode: "link_weight_gaussian"
  actor_mode: "magnneto_like"
  critic_mode: "magnneto_like"
  global_features: "none"
  edge_features: "LU"
  link_weights_as_input: True
  initial_exploration_coeff: -1.0
  scenario_presets:
    train:
      topology:
        graph: "magnneto_nsfnet_geant2"